### ISSUE TITLE
Bad pairing results in blank page

### ISSUE THREAD

**Issue by mmoayyed** [toopher/toopher-cas#1]
I have successfully managed to integrate the Toopher IFrame with my own CAS application. However, I have trouble resuming the flow session when pairing fails. I can see that the flow tries to authenticate the user and that fails correctly because my user doesn't yet exist. Then, the flow tries to pair the user and generates the page that allows me to download the apps and start pairing. I simply continue to pair, and provide an invalid pairing phrase. When I press enter on the pairing input box, I get a message that the paring phrase is invalid which is correct, but then the screen turns blank. 

What is the expected behavior here? Should the flow resume and put me back in a state where I can reauthenticate? Is it expected of me to put a "back" button somewhere on the page to allow the user to do just that? Is there way for the CAS app to be notified when pairing fails so that I can navigate the flow to a different place?

**Comment by mmoayyed** [comment]
I didnt know if I should create the issue here:
https://github.com/toopher/toopher-issues

If this is the wrong place let me know please and I'll move it over and submit a new one.

**Comment by dshafer** [comment]
Hi @mmoayyed - this the correct place to post Toopher-CAS issues.  https://github.com/toopher/toopher-issues was created as a place to host a catch-all issue tracker for projects that don't have their own Github repo yet.

Thanks for the bug report - we'll take a closer look at non-happy-path workflows in the pairing process with CAS and determine if this is something we can fix completely within the iframe, or if you will need to adjust your CAS flow to accommodate it.

**Comment by mmoayyed** [comment]
Thank you Drew. I'll move the issue over.

**Comment by dshafer** [comment]
Reopening - to clarify, this is the proper place for this issue.  We only use toopher-issues if there is not a more specific tracker available, which is not the case here.

**Comment by mmoayyed** [comment]
Ah, cool. thanks again for looking into this. I look forward to hearing from you.

Just to give you a bit more context, I am hoping that I could integrate the great work that you did into this project here: https://github.com/Unicon/cas-mfa

We have done several MFA deployments with CAS mostly with Duo and Radius at times, and it would be great if we could announce toopher support as well. Hopefully once we have resolved this issue.

**Comment by dshafer** [comment]
@mmoayyed - I am not able to replicate this error in our test environment.  We have a demo CAS deployment you can test out at https://sso-demo.toopher.com/cas-demo-app - can you attempt to access one of the toopher-protected sections there and see if you can replicate the issue?  Our demo app uses `SimpleTestUsernamePasswordAuthenticationHandler`, so you can pick any username and enter the same thing for the password.

**Comment by mmoayyed** [comment]
Thanks for the update. I tried a few times, but could not get it to reproduce, but at the same time, I think I am seeing a different UI. Let me look into my own CAS config and see comes out.

Do you have any pointers on a way to troubleshoot this? as I recall, upon entering a bad pairing phrase and receiving the error, the screen immediately goes blank. Any thoughts on why that might happen?

At the same time, can you confirm that what's hosted in this repo is the same exact configuration that is available in your demos?

**Comment by dshafer** [comment]
Yes, it is the same - I rebuilt and re-deployed cas.war this morning from the current `master` on this repo.  There is some configuration specific to the demo app (setting up the different LOA requirements for the various demo sections), but that should not impact the pairing process.  Everything else is unchanged from the config in the repo.

Do you have a deployment exhibiting the issue that I could try out?

**Comment by mmoayyed** [comment]
Excellent. Appreciate you confirming the changeset.

We do have a deployment here:
https://github.com/Unicon/cas-mfa

...which is comprised of various mfa-provider modules. For toopher:
1. Modify [this pom](https://github.com/Unicon/cas-mfa/blob/master/cas-mfa-overlay/pom.xml) to enable toopher dependencies in the overlay.
2. Move the [etc](https://github.com/Unicon/cas-mfa/tree/master/cas-mfa-overlay/etc) contents over to your /etc/cas
3. You may also want to modify the [registry](https://github.com/Unicon/cas-mfa/blob/master/cas-mfa-overlay/etc/servicesRegistry.conf) config to point to toopher-two-factor.

Then, access the CAS server with /cas/login?service=url&authn_method=toopher-two-factor

I am using my own toopher credentials to authenticate against toopher for now in dev mode. They are located in the cas.properties file.

Appreciate you reviewing this.

**Comment by mmoayyed** [comment]
I am also going to try deploying this repo and see if I can get it to fail for me. It's possible I missed something as I was porting over changes. (I deliberately skipped over the LOA config)

**Comment by dshafer** [comment]
heh - [found the problem](https://github.com/Unicon/cas-mfa/blob/master/cas-mfa-toopher-web/src/main/webapp/css/toopher-cas.css)

```
#toopher_iframe {
  height: 500px;
  width: 600%
}
```

I'm guessing this is a typo.  Changing `width` to something less than 100% fixes the issue.  The iframe is usable at 600% width as long as there are no errors, because all of the text inputs are on the left, and the missing buttons can be bypassed by hitting [enter] on the inputs.  When an error message pops up, though, it scrolls the iframe over to an area with no content, with no way to scroll it back (the design is specifically meant to prevent scrolling within the iframe).

Let me know if that change fixes the issue.  Cheers,
-DS

**Comment by mmoayyed** [comment]
Awesome. That does indeed fix the issue! Funny how sometimes something as trivial as that could turn up confusing outcomes :)

I very much appreciate your assistance. Just a few more questions:
- Yesterday, when I tried your demo I noticed that on the right hand side there's a link/button that allows SMS testing for pairing, I am not see that in my own iframe. Could this still be an iframe issue with the CSS width/height that prevents me from seeing it? or is this something I have to turn on in my toopher admin dashboard, etc?
- Incidentally, I went ahead and tried to run the demo again to exactly remember how I saw that SMS button/link and as I logged in using hello/hello to the "protected area" demo I got this stacktrace:

``` bash
java.io.FileNotFoundException: /usr/share/tomcat6/work/Catalina/localhost/cas/org/apache/jsp/WEB_002dINF/view/jsp/default_/ui/casToopherAuthView_jsp.java (Permission denied)
    java.io.FileOutputStream.open(Native Method)
    java.io.FileOutputStream.<init>(FileOutputStream.java:212)
    java.io.FileOutputStream.<init>(FileOutputStream.java:99)
    org.apache.jasper.compiler.Compiler.setupContextWriter(Compiler.java:276)
    org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:215)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:332)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:312)
    org.apache.jasper.compiler.Compiler.compile(Compiler.java:299)
    org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:589)
    org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:317)
    org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
    org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:238)
    org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:262)
    org.springframework.webflow.mvc.servlet.ServletMvcView.doRender(ServletMvcView.java:50)
    org.springframework.webflow.mvc.view.AbstractMvcView.render(AbstractMvcView.java:187)
    org.springframework.webflow.engine.ViewState.render(ViewState.java:296)
    org.springframework.webflow.engine.ViewState.doEnter(ViewState.java:186)
    org.springframework.webflow.engine.State.enter(State.java:194)
    org.springframework.webflow.engine.Transition.execute(Transition.java:227)
    org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:393)
    org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlContextImpl.java:214)
    org.springframework.webflow.engine.TransitionableState.handleEvent(TransitionableState.java:119)
    org.springframework.webflow.engine.Flow.handleEvent(Flow.java:555)
    org.springframework.webflow.engine.impl.FlowExecutionImpl.handleEvent(FlowExecutionImpl.java:388)
    org.springframework.webflow.engine.impl.RequestControlContextImpl.handleEvent(RequestControlContextImpl.java:210)
    org.springframework.webflow.engine.ActionState.doEnter(ActionState.java:105)
    org.springframework.webflow.engine.State.enter(State.java:194)
    org.springframework.webflow.engine.Transition.execute(Transition.java:227)
    org.springframework.webflow.engine.DecisionState.doEnter(DecisionState.java:51)
    org.springframework.webflow.engine.State.enter(State.java:194)
    org.springframework.webflow.engine.Transition.execute(Transition.java:227)
    org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:393)
    org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlContextImpl.java:214)
    org.springframework.webflow.engine.TransitionableState.handleEvent(TransitionableState.java:119)
    org.springframework.webflow.engine.Flow.handleEvent(Flow.java:555)
    org.springframework.webflow.engine.impl.FlowExecutionImpl.handleEvent(FlowExecutionImpl.java:388)
    org.springframework.webflow.engine.impl.RequestControlContextImpl.handleEvent(RequestControlContextImpl.java:210)
    org.springframework.webflow.engine.ActionState.doEnter(ActionState.java:105)
    org.springframework.webflow.engine.State.enter(State.java:194)
    org.springframework.webflow.engine.Transition.execute(Transition.java:227)
    org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:393)
    org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlContextImpl.java:214)
    org.springframework.webflow.engine.TransitionableState.handleEvent(TransitionableState.java:119)
    org.springframework.webflow.engine.Flow.handleEvent(Flow.java:555)
    org.springframework.webflow.engine.impl.FlowExecutionImpl.handleEvent(FlowExecutionImpl.java:388)
    org.springframework.webflow.engine.impl.RequestControlContextImpl.handleEvent(RequestControlContextImpl.java:210)
    org.springframework.webflow.engine.ViewState.handleEvent(ViewState.java:232)
    org.springframework.webflow.engine.ViewState.resume(ViewState.java:196)
    org.springframework.webflow.engine.Flow.resume(Flow.java:545)
    org.springframework.webflow.engine.impl.FlowExecutionImpl.resume(FlowExecutionImpl.java:261)
    org.springframework.webflow.executor.FlowExecutorImpl.resumeExecution(FlowExecutorImpl.java:169)
    org.springframework.webflow.mvc.servlet.FlowHandlerAdapter.handle(FlowHandlerAdapter.java:183)
    org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
    org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
    org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    org.jasig.cas.web.init.SafeDispatcherServlet.service_aroundBody2(SafeDispatcherServlet.java:128)
    org.jasig.cas.web.init.SafeDispatcherServlet.service_aroundBody3$advice(SafeDispatcherServlet.java:57)
    org.jasig.cas.web.init.SafeDispatcherServlet.service(SafeDispatcherServlet.java:1)
    org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
    com.github.inspektr.common.web.ClientInfoThreadLocalFilter.doFilter(ClientInfoThreadLocalFilter.java:63)
```

**Comment by dshafer** [comment]
Yes, SMS authentication is an add-on that requires that your requester be on the "Plus" plan.  The option doesn't show up otherwise.

The stack trace you saw should be cleared up.  It was caused by me inadvertently running the tomcat server as root while testing - this changed ownership of some files under /usr/share/tomcat6 so that the normal tomcat user was not able to properly execute the server any more.
